name: book_echo
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: 8.1.6

  # Helpful
  intl: 0.20.1
  flutter_dotenv: 5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/env/

flutter_intl:
  enabled: true
  arb_dir: lib/common/localization/l10n/
  output_dir: lib/common/localization/generated/
