name: book_echo
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: 8.1.6

  # Helpful
  intl: 0.19.0
  flutter_dotenv: 5.2.1
  equatable: 2.0.7

  # UI
  flutter_animate: 4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env

flutter_intl:
  enabled: true
  arb_dir: lib/common/localization/l10n/
  output_dir: lib/common/localization/generated/
